### ISSUE TITLE
Listing all packages used

### ISSUE THREAD

**Issue by ryan-hill** [ryan-hill/sfs-r-gis-2018#1]
Compiling a list of all packages I've used in my sections to update the "Before SFS" section:

library(sp)
library(maptools)
library(rgeos)
library(rgdal)
library(raster)
library(sf)
library(RCurl)
library(USAboundaries)
library(jsonlite)
library(geojsonio)

**Comment by fawda123** [comment]
Here are mine (after removing ones you cover):

library(devtools)
library(ggplot2) - dev
library(maps)
library(tmap)
library(micromap)
library(ggrepel)
library(plotly) - dev
library(ggmap)
library(mapview)
